version: "3"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: junkes001
    volumes: 
      - "./mysql-data:/var/lib/mysql"
    networks:
      - net001

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - net001

  api:
    depends_on:
      - mysql
      - redis
    image: node:12.16-alpine
    command: "npm run prod"
    restart: always
    ports:
      - "3000:3000"
    working_dir: "/home/node/app"
    volumes:
      - ./back:/home/node/app
    networks:
      - net001

  front-prod:
    image: node:12.16-alpine
    command: "npm run prod"
    working_dir: "/home/quasar/app"
    volumes:
      - ./front:/home/quasar/app

  apache:
    image: httpd:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./apache2/htdocs:/usr/local/apache2/htdocs/
      - ./apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net001

networks:
  net001:
    driver: "bridge"
